# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: ktunnel
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - "-s -w"
  hooks:
    post: ./compress_binaries.sh
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  draft: false
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"
  prerelease: auto
nfpms:
  # note that this is an array of nfpm configs
  -
    id: ktunnel
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
    - ktunnel

    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Tux
      windows: Windows
    homepage: https://github.com/omrikiei/ktunnel
    maintainer: omrikiei <omrieival@gmail.com>
    description: Ktunnel is a network tunneling tool for kubernetes
    license: MIT
    formats:
      - deb
      - rpm
      - exe

    bindir: /usr/bin
    epoch: 1

brews:
  -
    github:
      owner: omrikiei
      name: ktunnel

    commit_author:
      name: omrikiei
      email: omrieival@gmail.com

    homepage: "https://github.com/omrikiei/ktunnel"
    description: "Network tunneling tool for kubernetes."

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: auto

    # Custom block for brew.
    # Can be used to specify alternate downloads for devel or head releases.
    # Default is empty.
    custom_block: |
      head "https://github.com/omrikiei/ktunnel.git"
    test: |
      system "#{bin}/program version"
