# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktunnel < Formula
  desc "Network tunneling tool for kubernetes."
  homepage "https://github.com/omrikiei/ktunnel"
  version "1.5.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/omrikiei/ktunnel/releases/download/v1.5.1/ktunnel_ 1.5.1_Darwin_arm64.tar.gz"
      sha256 "de73251d5eae68ea005e93ff801fb85986d70251ca89f0c8e1f463bb9b2bf84d"

      def install
        bin.install "ktunnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/omrikiei/ktunnel/releases/download/v1.5.1/ktunnel_ 1.5.1_Darwin_x86_64.tar.gz"
      sha256 "4a5741d0b96b36960070dd1ac84fe8e6d35f2eea4e1893847f8a993edbf056ee"

      def install
        bin.install "ktunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/omrikiei/ktunnel/releases/download/v1.5.1/ktunnel_ 1.5.1_Linux_arm64.tar.gz"
      sha256 "fcb5fa066cdd37c6015eab56d71887a4e112ca18b07cb915ea24d77acef8a954"

      def install
        bin.install "ktunnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/omrikiei/ktunnel/releases/download/v1.5.1/ktunnel_ 1.5.1_Linux_x86_64.tar.gz"
      sha256 "d7f220cfe50ab7694d3a7616714dfa6de981634f97bcc68ed99bb1cd4787981d"

      def install
        bin.install "ktunnel"
      end
    end
  end

  head "https://github.com/omrikiei/ktunnel.git"

  test do
    system "#{bin}/program version"
  end
end
