// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tunnel.proto

package kube_tunnel

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogLevel int32

const (
	LogLevel_INFO    LogLevel = 0
	LogLevel_VERBOSE LogLevel = 1
	LogLevel_DEBUG   LogLevel = 2
	LogLevel_WARNING LogLevel = 3
	LogLevel_ERROR   LogLevel = 4
)

var LogLevel_name = map[int32]string{
	0: "INFO",
	1: "VERBOSE",
	2: "DEBUG",
	3: "WARNING",
	4: "ERROR",
}

var LogLevel_value = map[string]int32{
	"INFO":    0,
	"VERBOSE": 1,
	"DEBUG":   2,
	"WARNING": 3,
	"ERROR":   4,
}

func (x LogLevel) String() string {
	return proto.EnumName(LogLevel_name, int32(x))
}

func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f51ddaa7891a711, []int{0}
}

type TunnelScheme int32

const (
	TunnelScheme_TCP TunnelScheme = 0
	TunnelScheme_UDP TunnelScheme = 1
)

var TunnelScheme_name = map[int32]string{
	0: "TCP",
	1: "UDP",
}

var TunnelScheme_value = map[string]int32{
	"TCP": 0,
	"UDP": 1,
}

func (x TunnelScheme) String() string {
	return proto.EnumName(TunnelScheme_name, int32(x))
}

func (TunnelScheme) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f51ddaa7891a711, []int{1}
}

type LogMessage struct {
	LogLevel             LogLevel `protobuf:"varint,1,opt,name=logLevel,proto3,enum=grpc_tunnel.LogLevel" json:"logLevel,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogMessage) Reset()         { *m = LogMessage{} }
func (m *LogMessage) String() string { return proto.CompactTextString(m) }
func (*LogMessage) ProtoMessage()    {}
func (*LogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f51ddaa7891a711, []int{0}
}

func (m *LogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogMessage.Unmarshal(m, b)
}
func (m *LogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogMessage.Marshal(b, m, deterministic)
}
func (m *LogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMessage.Merge(m, src)
}
func (m *LogMessage) XXX_Size() int {
	return xxx_messageInfo_LogMessage.Size(m)
}
func (m *LogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LogMessage proto.InternalMessageInfo

func (m *LogMessage) GetLogLevel() LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return LogLevel_INFO
}

func (m *LogMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SocketDataRequest struct {
	Port                 int32        `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	LogLevel             LogLevel     `protobuf:"varint,2,opt,name=logLevel,proto3,enum=grpc_tunnel.LogLevel" json:"logLevel,omitempty"`
	Scheme               TunnelScheme `protobuf:"varint,3,opt,name=scheme,proto3,enum=grpc_tunnel.TunnelScheme" json:"scheme,omitempty"`
	Data                 []byte       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	ShouldClose          bool         `protobuf:"varint,5,opt,name=shouldClose,proto3" json:"shouldClose,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SocketDataRequest) Reset()         { *m = SocketDataRequest{} }
func (m *SocketDataRequest) String() string { return proto.CompactTextString(m) }
func (*SocketDataRequest) ProtoMessage()    {}
func (*SocketDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f51ddaa7891a711, []int{1}
}

func (m *SocketDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocketDataRequest.Unmarshal(m, b)
}
func (m *SocketDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocketDataRequest.Marshal(b, m, deterministic)
}
func (m *SocketDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocketDataRequest.Merge(m, src)
}
func (m *SocketDataRequest) XXX_Size() int {
	return xxx_messageInfo_SocketDataRequest.Size(m)
}
func (m *SocketDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SocketDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SocketDataRequest proto.InternalMessageInfo

func (m *SocketDataRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *SocketDataRequest) GetLogLevel() LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return LogLevel_INFO
}

func (m *SocketDataRequest) GetScheme() TunnelScheme {
	if m != nil {
		return m.Scheme
	}
	return TunnelScheme_TCP
}

func (m *SocketDataRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SocketDataRequest) GetShouldClose() bool {
	if m != nil {
		return m.ShouldClose
	}
	return false
}

type SocketDataResponse struct {
	HasErr               bool        `protobuf:"varint,1,opt,name=hasErr,proto3" json:"hasErr,omitempty"`
	LogMessage           *LogMessage `protobuf:"bytes,2,opt,name=logMessage,proto3" json:"logMessage,omitempty"`
	Data                 []byte      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ShouldClose          bool        `protobuf:"varint,4,opt,name=shouldClose,proto3" json:"shouldClose,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SocketDataResponse) Reset()         { *m = SocketDataResponse{} }
func (m *SocketDataResponse) String() string { return proto.CompactTextString(m) }
func (*SocketDataResponse) ProtoMessage()    {}
func (*SocketDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f51ddaa7891a711, []int{2}
}

func (m *SocketDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocketDataResponse.Unmarshal(m, b)
}
func (m *SocketDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocketDataResponse.Marshal(b, m, deterministic)
}
func (m *SocketDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocketDataResponse.Merge(m, src)
}
func (m *SocketDataResponse) XXX_Size() int {
	return xxx_messageInfo_SocketDataResponse.Size(m)
}
func (m *SocketDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SocketDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SocketDataResponse proto.InternalMessageInfo

func (m *SocketDataResponse) GetHasErr() bool {
	if m != nil {
		return m.HasErr
	}
	return false
}

func (m *SocketDataResponse) GetLogMessage() *LogMessage {
	if m != nil {
		return m.LogMessage
	}
	return nil
}

func (m *SocketDataResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SocketDataResponse) GetShouldClose() bool {
	if m != nil {
		return m.ShouldClose
	}
	return false
}

func init() {
	proto.RegisterEnum("grpc_tunnel.LogLevel", LogLevel_name, LogLevel_value)
	proto.RegisterEnum("grpc_tunnel.TunnelScheme", TunnelScheme_name, TunnelScheme_value)
	proto.RegisterType((*LogMessage)(nil), "grpc_tunnel.LogMessage")
	proto.RegisterType((*SocketDataRequest)(nil), "grpc_tunnel.SocketDataRequest")
	proto.RegisterType((*SocketDataResponse)(nil), "grpc_tunnel.SocketDataResponse")
}

func init() { proto.RegisterFile("tunnel.proto", fileDescriptor_6f51ddaa7891a711) }

var fileDescriptor_6f51ddaa7891a711 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xd1, 0xae, 0xd2, 0x40,
	0x10, 0x65, 0x69, 0x29, 0x65, 0x8a, 0xa6, 0x6e, 0xa2, 0x56, 0x1f, 0xb4, 0xe9, 0x53, 0xc3, 0x03,
	0x11, 0x7c, 0xf0, 0x59, 0x68, 0x25, 0x24, 0x08, 0x64, 0x0b, 0x1a, 0x4d, 0x8c, 0x29, 0xb0, 0x29,
	0x86, 0xd2, 0xad, 0xdd, 0xed, 0xfd, 0x99, 0xfb, 0x39, 0xf7, 0xc7, 0x6e, 0xba, 0x2d, 0xa4, 0x5c,
	0x42, 0x72, 0x9f, 0x76, 0xe6, 0xcc, 0x99, 0x9d, 0x39, 0x67, 0x17, 0xba, 0x22, 0x4f, 0x12, 0x1a,
	0xf7, 0xd3, 0x8c, 0x09, 0x86, 0x8d, 0x28, 0x4b, 0xb7, 0x7f, 0x4b, 0xc8, 0xf9, 0x05, 0x30, 0x63,
	0xd1, 0x77, 0xca, 0x79, 0x18, 0x51, 0x3c, 0x00, 0x3d, 0x66, 0xd1, 0x8c, 0xde, 0xd1, 0xd8, 0x42,
	0x36, 0x72, 0x5f, 0x0e, 0x5f, 0xf7, 0x6b, 0xec, 0xfe, 0xac, 0x2a, 0x92, 0x33, 0x0d, 0x5b, 0xd0,
	0x3e, 0x96, 0xdd, 0x56, 0xd3, 0x46, 0x6e, 0x87, 0x9c, 0x52, 0xe7, 0x01, 0xc1, 0xab, 0x80, 0x6d,
	0x0f, 0x54, 0x78, 0xa1, 0x08, 0x09, 0xfd, 0x9f, 0x53, 0x2e, 0x30, 0x06, 0x35, 0x65, 0x99, 0x90,
	0xd7, 0xb7, 0x88, 0x8c, 0x2f, 0xc6, 0x36, 0x9f, 0x37, 0x76, 0x00, 0x1a, 0xdf, 0xee, 0xe9, 0x91,
	0x5a, 0x8a, 0x6c, 0x78, 0x77, 0xd1, 0xb0, 0x92, 0x47, 0x20, 0x09, 0xa4, 0x22, 0x16, 0x93, 0x77,
	0xa1, 0x08, 0x2d, 0xd5, 0x46, 0x6e, 0x97, 0xc8, 0x18, 0xdb, 0x60, 0xf0, 0x3d, 0xcb, 0xe3, 0xdd,
	0x38, 0x66, 0x9c, 0x5a, 0x2d, 0x1b, 0xb9, 0x3a, 0xa9, 0x43, 0xce, 0x3d, 0x02, 0x5c, 0x57, 0xc1,
	0x53, 0x96, 0x70, 0x8a, 0xdf, 0x80, 0xb6, 0x0f, 0xb9, 0x9f, 0x65, 0x52, 0x88, 0x4e, 0xaa, 0x0c,
	0x7f, 0x01, 0x88, 0xcf, 0x7e, 0x4a, 0x31, 0xc6, 0xf0, 0xed, 0x53, 0x31, 0x55, 0x99, 0xd4, 0xa8,
	0xe7, 0xed, 0x94, 0xdb, 0xdb, 0xa9, 0x57, 0xdb, 0xf5, 0x3c, 0xd0, 0x4f, 0xe6, 0x60, 0x1d, 0xd4,
	0xe9, 0xfc, 0xdb, 0xc2, 0x6c, 0x60, 0x03, 0xda, 0x3f, 0x7c, 0x32, 0x5a, 0x04, 0xbe, 0x89, 0x70,
	0x07, 0x5a, 0x9e, 0x3f, 0x5a, 0x4f, 0xcc, 0x66, 0x81, 0xff, 0xfc, 0x4a, 0xe6, 0xd3, 0xf9, 0xc4,
	0x54, 0x0a, 0xdc, 0x27, 0x64, 0x41, 0x4c, 0xb5, 0x67, 0x43, 0xb7, 0xee, 0x18, 0x6e, 0x83, 0xb2,
	0x1a, 0x2f, 0xcd, 0x46, 0x11, 0xac, 0xbd, 0xa5, 0x89, 0x86, 0x7f, 0x40, 0x2b, 0x19, 0x38, 0x00,
	0x98, 0x26, 0xff, 0x44, 0x95, 0x7d, 0xb8, 0x90, 0x76, 0xf5, 0xda, 0xef, 0x3f, 0xde, 0xac, 0x97,
	0x3e, 0x3a, 0x0d, 0x17, 0x7d, 0x42, 0xa3, 0x17, 0xbf, 0x8d, 0x43, 0xbe, 0xa1, 0x15, 0x6f, 0xa3,
	0xc9, 0x8f, 0xfa, 0xf9, 0x31, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x01, 0x5a, 0xaa, 0xb8, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TunnelClient is the client API for Tunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TunnelClient interface {
	InitTunnel(ctx context.Context, opts ...grpc.CallOption) (Tunnel_InitTunnelClient, error)
}

type tunnelClient struct {
	cc *grpc.ClientConn
}

func NewTunnelClient(cc *grpc.ClientConn) TunnelClient {
	return &tunnelClient{cc}
}

func (c *tunnelClient) InitTunnel(ctx context.Context, opts ...grpc.CallOption) (Tunnel_InitTunnelClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tunnel_serviceDesc.Streams[0], "/grpc_tunnel.Tunnel/InitTunnel", opts...)
	if err != nil {
		return nil, err
	}
	x := &tunnelInitTunnelClient{stream}
	return x, nil
}

type Tunnel_InitTunnelClient interface {
	Send(*SocketDataRequest) error
	Recv() (*SocketDataResponse, error)
	grpc.ClientStream
}

type tunnelInitTunnelClient struct {
	grpc.ClientStream
}

func (x *tunnelInitTunnelClient) Send(m *SocketDataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tunnelInitTunnelClient) Recv() (*SocketDataResponse, error) {
	m := new(SocketDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TunnelServer is the server API for Tunnel service.
type TunnelServer interface {
	InitTunnel(Tunnel_InitTunnelServer) error
}

// UnimplementedTunnelServer can be embedded to have forward compatible implementations.
type UnimplementedTunnelServer struct {
}

func (*UnimplementedTunnelServer) InitTunnel(srv Tunnel_InitTunnelServer) error {
	return status.Errorf(codes.Unimplemented, "method InitTunnel not implemented")
}

func RegisterTunnelServer(s *grpc.Server, srv TunnelServer) {
	s.RegisterService(&_Tunnel_serviceDesc, srv)
}

func _Tunnel_InitTunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServer).InitTunnel(&tunnelInitTunnelServer{stream})
}

type Tunnel_InitTunnelServer interface {
	Send(*SocketDataResponse) error
	Recv() (*SocketDataRequest, error)
	grpc.ServerStream
}

type tunnelInitTunnelServer struct {
	grpc.ServerStream
}

func (x *tunnelInitTunnelServer) Send(m *SocketDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tunnelInitTunnelServer) Recv() (*SocketDataRequest, error) {
	m := new(SocketDataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Tunnel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_tunnel.Tunnel",
	HandlerType: (*TunnelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InitTunnel",
			Handler:       _Tunnel_InitTunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tunnel.proto",
}
