// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/tunnel.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_INFO    LogLevel = 0
	LogLevel_VERBOSE LogLevel = 1
	LogLevel_DEBUG   LogLevel = 2
	LogLevel_WARNING LogLevel = 3
	LogLevel_ERROR   LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "INFO",
		1: "VERBOSE",
		2: "DEBUG",
		3: "WARNING",
		4: "ERROR",
	}
	LogLevel_value = map[string]int32{
		"INFO":    0,
		"VERBOSE": 1,
		"DEBUG":   2,
		"WARNING": 3,
		"ERROR":   4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_tunnel_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_api_tunnel_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_tunnel_proto_rawDescGZIP(), []int{0}
}

type TunnelScheme int32

const (
	TunnelScheme_TCP TunnelScheme = 0
	TunnelScheme_UDP TunnelScheme = 1
)

// Enum value maps for TunnelScheme.
var (
	TunnelScheme_name = map[int32]string{
		0: "TCP",
		1: "UDP",
	}
	TunnelScheme_value = map[string]int32{
		"TCP": 0,
		"UDP": 1,
	}
)

func (x TunnelScheme) Enum() *TunnelScheme {
	p := new(TunnelScheme)
	*p = x
	return p
}

func (x TunnelScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_api_tunnel_proto_enumTypes[1].Descriptor()
}

func (TunnelScheme) Type() protoreflect.EnumType {
	return &file_api_tunnel_proto_enumTypes[1]
}

func (x TunnelScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelScheme.Descriptor instead.
func (TunnelScheme) EnumDescriptor() ([]byte, []int) {
	return file_api_tunnel_proto_rawDescGZIP(), []int{1}
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogLevel      LogLevel               `protobuf:"varint,1,opt,name=logLevel,proto3,enum=grpc_tunnel.LogLevel" json:"logLevel,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_api_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_api_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *LogMessage) GetLogLevel() LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return LogLevel_INFO
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SocketDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	RequestID     string                 `protobuf:"bytes,2,opt,name=requestID,proto3" json:"requestID,omitempty"`
	LogLevel      LogLevel               `protobuf:"varint,3,opt,name=logLevel,proto3,enum=grpc_tunnel.LogLevel" json:"logLevel,omitempty"`
	Scheme        TunnelScheme           `protobuf:"varint,4,opt,name=scheme,proto3,enum=grpc_tunnel.TunnelScheme" json:"scheme,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	ShouldClose   bool                   `protobuf:"varint,6,opt,name=shouldClose,proto3" json:"shouldClose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocketDataRequest) Reset() {
	*x = SocketDataRequest{}
	mi := &file_api_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketDataRequest) ProtoMessage() {}

func (x *SocketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketDataRequest.ProtoReflect.Descriptor instead.
func (*SocketDataRequest) Descriptor() ([]byte, []int) {
	return file_api_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *SocketDataRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SocketDataRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *SocketDataRequest) GetLogLevel() LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return LogLevel_INFO
}

func (x *SocketDataRequest) GetScheme() TunnelScheme {
	if x != nil {
		return x.Scheme
	}
	return TunnelScheme_TCP
}

func (x *SocketDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SocketDataRequest) GetShouldClose() bool {
	if x != nil {
		return x.ShouldClose
	}
	return false
}

type SocketDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasErr        bool                   `protobuf:"varint,1,opt,name=hasErr,proto3" json:"hasErr,omitempty"`
	LogMessage    *LogMessage            `protobuf:"bytes,2,opt,name=logMessage,proto3" json:"logMessage,omitempty"`
	RequestID     string                 `protobuf:"bytes,3,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	ShouldClose   bool                   `protobuf:"varint,5,opt,name=shouldClose,proto3" json:"shouldClose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocketDataResponse) Reset() {
	*x = SocketDataResponse{}
	mi := &file_api_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocketDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketDataResponse) ProtoMessage() {}

func (x *SocketDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketDataResponse.ProtoReflect.Descriptor instead.
func (*SocketDataResponse) Descriptor() ([]byte, []int) {
	return file_api_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *SocketDataResponse) GetHasErr() bool {
	if x != nil {
		return x.HasErr
	}
	return false
}

func (x *SocketDataResponse) GetLogMessage() *LogMessage {
	if x != nil {
		return x.LogMessage
	}
	return nil
}

func (x *SocketDataResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *SocketDataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SocketDataResponse) GetShouldClose() bool {
	if x != nil {
		return x.ShouldClose
	}
	return false
}

var File_api_tunnel_proto protoreflect.FileDescriptor

const file_api_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x10api/tunnel.proto\x12\vgrpc_tunnel\"Y\n" +
	"\n" +
	"LogMessage\x121\n" +
	"\blogLevel\x18\x01 \x01(\x0e2\x15.grpc_tunnel.LogLevelR\blogLevel\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe1\x01\n" +
	"\x11SocketDataRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x1c\n" +
	"\trequestID\x18\x02 \x01(\tR\trequestID\x121\n" +
	"\blogLevel\x18\x03 \x01(\x0e2\x15.grpc_tunnel.LogLevelR\blogLevel\x121\n" +
	"\x06scheme\x18\x04 \x01(\x0e2\x19.grpc_tunnel.TunnelSchemeR\x06scheme\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12 \n" +
	"\vshouldClose\x18\x06 \x01(\bR\vshouldClose\"\xb9\x01\n" +
	"\x12SocketDataResponse\x12\x16\n" +
	"\x06hasErr\x18\x01 \x01(\bR\x06hasErr\x127\n" +
	"\n" +
	"logMessage\x18\x02 \x01(\v2\x17.grpc_tunnel.LogMessageR\n" +
	"logMessage\x12\x1c\n" +
	"\trequestID\x18\x03 \x01(\tR\trequestID\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12 \n" +
	"\vshouldClose\x18\x05 \x01(\bR\vshouldClose*D\n" +
	"\bLogLevel\x12\b\n" +
	"\x04INFO\x10\x00\x12\v\n" +
	"\aVERBOSE\x10\x01\x12\t\n" +
	"\x05DEBUG\x10\x02\x12\v\n" +
	"\aWARNING\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04* \n" +
	"\fTunnelScheme\x12\a\n" +
	"\x03TCP\x10\x00\x12\a\n" +
	"\x03UDP\x10\x012]\n" +
	"\x06Tunnel\x12S\n" +
	"\n" +
	"InitTunnel\x12\x1e.grpc_tunnel.SocketDataRequest\x1a\x1f.grpc_tunnel.SocketDataResponse\"\x00(\x010\x01B\aZ\x05./apib\x06proto3"

var (
	file_api_tunnel_proto_rawDescOnce sync.Once
	file_api_tunnel_proto_rawDescData []byte
)

func file_api_tunnel_proto_rawDescGZIP() []byte {
	file_api_tunnel_proto_rawDescOnce.Do(func() {
		file_api_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tunnel_proto_rawDesc), len(file_api_tunnel_proto_rawDesc)))
	})
	return file_api_tunnel_proto_rawDescData
}

var file_api_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_tunnel_proto_goTypes = []any{
	(LogLevel)(0),              // 0: grpc_tunnel.LogLevel
	(TunnelScheme)(0),          // 1: grpc_tunnel.TunnelScheme
	(*LogMessage)(nil),         // 2: grpc_tunnel.LogMessage
	(*SocketDataRequest)(nil),  // 3: grpc_tunnel.SocketDataRequest
	(*SocketDataResponse)(nil), // 4: grpc_tunnel.SocketDataResponse
}
var file_api_tunnel_proto_depIdxs = []int32{
	0, // 0: grpc_tunnel.LogMessage.logLevel:type_name -> grpc_tunnel.LogLevel
	0, // 1: grpc_tunnel.SocketDataRequest.logLevel:type_name -> grpc_tunnel.LogLevel
	1, // 2: grpc_tunnel.SocketDataRequest.scheme:type_name -> grpc_tunnel.TunnelScheme
	2, // 3: grpc_tunnel.SocketDataResponse.logMessage:type_name -> grpc_tunnel.LogMessage
	3, // 4: grpc_tunnel.Tunnel.InitTunnel:input_type -> grpc_tunnel.SocketDataRequest
	4, // 5: grpc_tunnel.Tunnel.InitTunnel:output_type -> grpc_tunnel.SocketDataResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_tunnel_proto_init() }
func file_api_tunnel_proto_init() {
	if File_api_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tunnel_proto_rawDesc), len(file_api_tunnel_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tunnel_proto_goTypes,
		DependencyIndexes: file_api_tunnel_proto_depIdxs,
		EnumInfos:         file_api_tunnel_proto_enumTypes,
		MessageInfos:      file_api_tunnel_proto_msgTypes,
	}.Build()
	File_api_tunnel_proto = out.File
	file_api_tunnel_proto_goTypes = nil
	file_api_tunnel_proto_depIdxs = nil
}
